const assert=require('node:assert/strict');
const E=require('../dist/game.js');
const W=require('../dist/world.js');
const master=W.fresh();
W.validate(master);
assert.equal(master.clubs.length,74);
assert.equal(master.clubs.filter(c=>c.div===0).length,12);
assert.equal(master.clubs.filter(c=>c.div===1).length,10);
assert.equal(master.clubs.filter(c=>c.div===2).length,18);
assert.equal(master.competitions.length,4);
assert.equal(master.competitions[0].engineMode,'league');
assert.equal(master.competitions[1].engineMode,'league');
assert.equal(master.competitions[2].engineMode,'cup');
assert.equal(master.competitions[3].engineMode,'feeder');
assert.equal(master.competitions[2].participants.length,64);
assert.equal(new Set(master.competitions[2].participants).size,64);
assert.equal(master.competitions[3].shortName,'Promotion League');
assert.equal(master.competitions[2].participants.includes(15),false,'FC Vaduz is not a Swiss Cup participant');

const extra={id:4,name:'Taça Experimental',shortName:'Experimental',country:'Suíça',kind:'Taça',format:'Eliminatórias',engineMode:'cup',pointsWin:3,pointsDraw:1,pointsLoss:0,participants:[0,12,13,14],notes:'Teste',logo:'data:image/png;base64,AAAA',trophy:'data:image/png;base64,AAAA'};
const expanded={...master,competitions:[...master.competitions,extra]};
W.validate(expanded);
const career=W.createCareer(expanded,12);
assert.equal(career.competitions.length,5);
assert.notEqual(career.competitions,expanded.competitions);
assert.deepEqual(career.competitions.find(c=>c.id===4).participants,[0,12,13,14]);
assert.ok(E.cupState(career,4),'Custom playable cup gets its own career state');
expanded.competitions.find(c=>c.id===4).name='Mudou na Mestre';
assert.equal(career.competitions.find(c=>c.id===4).name,'Taça Experimental');
assert.throws(()=>W.validate({...expanded,competitions:[...expanded.competitions,{...extra,id:5,participants:[999]}]}));
assert.throws(()=>W.validate({...expanded,competitions:expanded.competitions.map(c=>c.id===4?{...c,participants:[0,12,13]}:c)}),'Playable cups require a power-of-two field');
const catalogueOnly={...expanded,competitions:expanded.competitions.filter(c=>c.id!==0)};W.validate(catalogueOnly);assert.throws(()=>W.createCareer(catalogueOnly,12),'Missing simulation leagues still block careers');
E.validate(career);
console.log('PASS: expandable competition model, 74-club pyramid, 64-team Swiss Cup, feeder league, custom playable cup and career snapshot isolation.');
