const assert=require('node:assert/strict'),W=require('../dist/world.js'),E=require('../dist/game.js'),Ops=require('../dist/database-ops.js'),C=require('../dist/csv-import.js');
const m=W.fresh(),id=m.players[0].id,staff=m.staff[0].id,baseline=JSON.stringify(m),career=W.createCareer(m,12);
for(const type of Object.keys(C.types)){assert(C.template(type).startsWith('\ufeff'));if(['players','clubs','staff','competitions'].includes(type))assert.equal(C.plan(m,type,Ops.exportCsv(m,type)).summary.length,0,type+' export roundtrip');}
const updates={clubs:'id;name\n0;Clube revisto',staff:`id;name\n${staff};Nome revisto`,competitions:'id;name\n0;Liga revista',players:`id;height\n${id};182`};
for(const [type,text] of Object.entries(updates)){const p=C.plan(m,type,text);assert.equal(p.summary.length,1);W.validate(p.candidate);}
const creations={players:'id;name;position\nNOVO;Jogador importado;MC',clubs:'id;name\nNOVO;Novo clube',staff:'id;name;role;club\nNOVO;Novo staff;Analista;0',competitions:'id;name\nNOVO;Competição documental'};
for(const [type,text] of Object.entries(creations)){const p=C.plan(m,type,text);assert(p.summary[0].created);assert.equal(p.candidate[type].length,m[type].length+1);assert.equal(p.candidate[type].at(-1).name,text.split('\n')[1].split(';')[1]);W.validate(p.candidate);}
const contents={international:`player_id;index;nation;level;caps;goals;startDate\n${id};NOVO;Suíça;Sub-21;3;0;2020-01-01`,contracts:`player_id;index;clubName;clubCountry;contractStart;contractEnd\n${id};NOVO;Clube externo;Portugal;2020-01-01;2021-01-01`,transfers:`player_id;index;fromClub;toClub;type;date\n${id};NOVO;1;0;Transferência;2022-01-01`,sources:`player_id;index;title;field;url;status\n${id};NOVO;Federação;international;https://example.org;Confirmado`};
const prop={international:'internationalRecords',contracts:'contractHistory',transfers:'transferHistory',sources:'documentSources'};
for(const [type,text] of Object.entries(contents)){const plan=C.plan(m,type,text),p=plan.candidate.players[0];assert.equal(p[prop[type]].length,1);assert.equal(p.club,m.players[0].club);assert.equal(C.plan(plan.candidate,type,Ops.exportCsv(plan.candidate,type)).summary.length,0,type+' linked roundtrip');W.validate(plan.candidate);}
const legacy=structuredClone(m);legacy.players[0].source='Arquivo';legacy.players[0].sourceUrl='Página de um livro';legacy.players[0].verificationStatus='Parcial';const sourcePlan=C.plan(legacy,'sources',`player_id;index;title\n${id};0;Arquivo revisto`);assert.equal(sourcePlan.candidate.players[0].documentSources[0].title,'Arquivo revisto');assert(sourcePlan.candidate.players[0].documentSources[0].notes.includes('Página de um livro'));assert.equal(sourcePlan.candidate.players[0].source,'Arquivo');
const loan=C.plan(m,'transfers',`player_id;index;fromClub;toClub;type;loan_parent_club;loan_start;loan_end;loan_purchase_type\n${id};NOVO;0;1;Empréstimo;0;2020-01-01;2021-01-01;Sem opção`);assert.equal(loan.candidate.players[0].transferHistory[0].loan.parentClub,0);assert.equal(loan.candidate.players[0].loan,undefined);assert.equal(C.plan(loan.candidate,'transfers',Ops.exportCsv(loan.candidate,'transfers')).summary.length,0);
const rebalanced=C.plan(m,'clubs','id;div\n0;1').candidate;W.validate(rebalanced);assert.throws(()=>W.createCareer(rebalanced,12),'Incomplete league composition still blocks careers');
const bad=[['staff',`id;name\n${staff};Bom\n999999;Inválido`],['international',`player_id;index;nation;level;caps\n${id};NOVO;Suíça;Principal;-1`],['contracts',`player_id;index;club;contractStart;contractEnd\n${id};NOVO;0;2021-01-01;2020-01-01`],['sources',`player_id;index;title;url\n${id};NOVO;Fonte;javascript:alert(1)`],['transfers',`player_id;index;fromClub;toClub\n${id};NOVO;999999;0`],['players','id;name;position\nNOVO;Nome;XYZ']];
for(const [type,text] of bad)assert.throws(()=>C.plan(m,type,text),type+' invalid import');
assert.throws(()=>C.plan(m,'statistics','player_id\n0'));
assert.equal(JSON.stringify(m),baseline);assert.equal(career.players.length,m.players.length);
const nested=structuredClone(m);nested.clubs[0].sponsors=[{name:'Patrocinador',image:''}];const isolated=C.plan(nested,'clubs','id;name\n0;Alterado');isolated.candidate.clubs[0].sponsors[0].name='Outra alteração';assert.equal(nested.clubs[0].sponsors[0].name,'Patrocinador');
console.log('PASS: every CSV category, new IDs, lossless roundtrips, legacy sources, historical loans, record validation, atomic failures and nested isolation.');
