const assert=require('node:assert/strict'),E=require('../dist/game.js'),W=require('../dist/world.js'),Ops=require('../dist/database-ops.js');
const master=W.fresh(),s=W.context(master),p=master.players[0],id=p.id;
const original=JSON.stringify(master);W.validate(master);assert.equal(JSON.stringify(master),original);
E.updatePlayer(s,id,{height:182});assert(p.changeHistory?.length);const entry=p.changeHistory.at(-1);assert(entry.changes.some(c=>c.field==='height'&&c.after==='182'));
const count=p.changeHistory.length;E.updatePlayer(s,id,{height:182});assert.equal(p.changeHistory.length,count,'Unchanged data creates no audit entry');
const valid=JSON.stringify(p);assert.throws(()=>E.updatePlayer(s,id,{height:999}));assert.equal(JSON.stringify(p),valid,'Rejected edits cannot alter the audit trail');
const career=W.createCareer(master,12);E.updatePlayer(s,id,{weight:80});assert.equal(career.players[0].changeHistory.length,count);
const second=master.players[1],before=JSON.stringify(master),plan=Ops.bulkPlan(master,[id,second.id],{type:'verification',value:'Confirmado'});
assert.equal(JSON.stringify(master),before,'Preview does not apply changes');assert.equal(plan.summary.length,2);assert.equal(plan.candidate.players[0].verificationStatus,'Confirmado');W.validate(plan.candidate);
const moved=Ops.bulkPlan(master,[id],{type:'club',value:1});assert.equal(moved.candidate.players[0].transferHistory.at(-1).toClub,1);assert.equal(moved.candidate.players[0].club,1);assert.equal(master.players[0].club,0);
assert.throws(()=>Ops.bulkPlan(master,[id],{type:'skills',value:99}));assert.throws(()=>Ops.bulkPlan(master,[id,id],{type:'status',value:'Retirado'}));assert.throws(()=>Ops.bulkPlan(master,[id],{type:'club',value:99999}));
const withLoan=structuredClone(master);withLoan.players[1].status='Emprestado';withLoan.players[1].loan={parentClub:1,startDate:'2026-01-01',endDate:'2027-01-01'};const unchanged=JSON.stringify(withLoan);assert.throws(()=>Ops.bulkPlan(withLoan,[id,second.id],{type:'club',value:2}));assert.equal(JSON.stringify(withLoan),unchanged,'One invalid row cancels the complete batch');
const source={title:'Clube',url:'https://example.org',consultedAt:'',field:'general',notes:'',status:'Por verificar'};
const refs=Ops.bulkPlan(master,[id],{type:'source',source});assert.equal(refs.candidate.players[0].documentSources[0].title,'Clube');assert(refs.candidate.players[0].changeHistory.at(-1).changes.some(c=>c.field==='documentSources'));
const csvSample=structuredClone(master);csvSample.players[0].name='=HYPERLINK("bad")';csvSample.players[1].name='Nome; com "aspas"\ne acento á';
const csv=Ops.exportCsv(csvSample,'players');assert(csv.startsWith('\ufeff'));assert(csv.includes("'"+'=HYPERLINK'));assert(csv.includes('Nome; com ""aspas""\ne acento á'));assert(!csv.includes('data:image'));
for(const type of ['players','clubs','staff','transfers','international','sources','statistics']){const t=Ops.table(master,type);assert(t.columns.length);assert.equal(Ops.exportCsv(master,type).split('\r\n')[0], '\ufeff'+t.columns.map(k=>'"'+k+'"').join(';'));}
const legacy={...p,internationalRecords:undefined,caps:0,internationalGoals:undefined,representedNation:'',internationalLevel:'Por indicar'};delete legacy.changeHistory;
const clone={...master,players:master.players.map(x=>x.id===id?legacy:x)},ctx=W.context(clone);E.updatePlayer(ctx,id,{internationalRecords:E.internationalRows(legacy)});assert(!legacy.changeHistory,'Adapting an old international record is not a factual change');
console.log('PASS: optional audit compatibility, no-op/failed edits, isolated bulk preview, atomic batches, transfers, source audit and safe CSV exports.');
assert.equal(Ops.importPlayersPlan(csvSample,csv).summary.length,0,'Export/import roundtrip preserves quoted and formula-prefixed values');
assert.deepEqual(Ops.parseCsv('\ufeffid,name\r\n1,"Nome, com ""aspas""\ne linha"').rows,[{id:'1',name:'Nome, com "aspas"\ne linha'}]);
for(const bad of ['id;id\n1;1','id;name\n1;"ab','id;name\n1;a;b'])assert.throws(()=>Ops.parseCsv(bad));
const baseline=JSON.stringify(master),imported=Ops.importPlayersPlan(master,`id;height;club\n${id};183;1`);
assert.equal(JSON.stringify(master),baseline);assert.equal(imported.candidate.players[0].height,183);assert.equal(imported.candidate.players[0].transferHistory.at(-1).toClub,1);assert.equal(career.players[0].club,0);
assert.equal(Ops.importPlayersPlan(master,`id;name;height\n${id};;`).summary.length,0);
for(const bad of [`id;height\n${id};183\n${second.id};999`,`id;skills\n${id};99`,`id;name\n${id};A\n${id};B`,'id;name\n999999;A'])assert.throws(()=>Ops.importPlayersPlan(master,bad));
assert.equal(JSON.stringify(master),baseline,'Invalid imports are atomic');
assert.throws(()=>Ops.importPlayersPlan(withLoan,`id;club\n${second.id};2`));
assert.throws(()=>Ops.importPlayersPlan(master,'id;height\n'+master.players.slice(0,201).map(p=>`${p.id};${p.height===182?183:182}`).join('\n')));
E.updatePlayer(s,id,{photoZoom:140,photoX:-10,photoY:20});assert.equal(p.photoZoom,140);const framed=JSON.stringify(p);assert.throws(()=>E.updatePlayer(s,id,{photoZoom:201}));assert.equal(JSON.stringify(p),framed);
console.log('PASS: CSV roundtrip, multiline parsing, reviewed updates, atomic rejection, loan protection, batch limits and portrait framing validation.');
