const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const {JSDOM}=require('jsdom'),{IDBFactory}=require('fake-indexeddb');
const root=path.resolve(__dirname,'../dist'),windows=[];
async function open(factory,html){
 const dom=new JSDOM(html||fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://documentary.test/',runScripts:'outside-only'}),w=dom.window;windows.push(w);w.indexedDB=factory;w.structuredClone=structuredClone;w.confirm=()=>true;w.HTMLElement.prototype.scrollIntoView=function(){};
 w.HTMLDialogElement.prototype.showModal=function(){this.setAttribute('open','');};w.HTMLDialogElement.prototype.close=function(){this.removeAttribute('open');};
 const run=code=>vm.runInContext(code,dom.getInternalVMContext()),$=id=>w.document.getElementById(id);
 for(const tag of w.document.querySelectorAll('script'))run(tag.src?fs.readFileSync(path.join(root,tag.getAttribute('src')),'utf8'):tag.textContent);
 for(let i=0;i<300&&w.document.body.classList.contains('storage-loading');i++)await new Promise(r=>setTimeout(r,10));
 assert(!w.document.body.classList.contains('storage-loading'));await run('AutoSave.settle()');w.settleForTest=()=>run('AutoSave.settle()');return {w,run,$};
}
async function main(){
 const visual=await open(new IDBFactory());visual.run('enterDatabase();master.players[0].photo="data:image/png;base64,iVBORw0KGgo=";master.players[0].photoZoom=125;master.players[0].nation="Suíça";master.players[0].secondNation="Portugal";master.players[0].theme="gold";master.players[0].internationalRecords=[{nation:"Suíça",level:"Sub-19",caps:3,goals:0},{nation:"Suíça",level:"Sub-21",caps:5,goals:0},{nation:"Suíça",level:"Principal",caps:11,goals:0}];openFilteredPlayers({query:master.players[0].name})');
 assert.match(visual.$('searchResults').textContent,/Portugal/);assert.match(visual.$('searchResults').textContent,/Suíça/);visual.$('viewCards').click();
 const vid=visual.run('master.players[0].id'),vcard=visual.$('searchResults').querySelector(`[data-card-player="${vid}"] .sticker`);assert(vcard);assert.equal(vcard.querySelector('.portrait img').getAttribute('src'),visual.run('master.players[0].photo'));assert.match(vcard.querySelector('.portrait img').style.transform,/1.25/);assert.equal(vcard.querySelector('.sticker-international b').textContent,'11');assert.equal(vcard.querySelector('.sticker-international span').textContent,'INT A');assert(!vcard.querySelector('.sticker-bottom').textContent.includes('anos'));
 visual.run('openPlayer(master.players[0].id)');assert.equal(visual.$('playerEditor').querySelector('.portrait img').getAttribute('src'),vcard.querySelector('.portrait img').getAttribute('src'));visual.$('playerCancel').click();
 assert.match(visual.run('stickerInternational({theme:"silver",internationalRecords:[{level:"Sub-19",caps:3},{level:"Sub-21",caps:5}]})'),/>8<\/b>/);assert.equal(visual.run('stickerInternational({theme:"base",caps:12,internationalLevel:"Principal"})'),'');assert.equal(visual.run('stickerInternational({theme:"gold",internationalRecords:[{level:"Principal",caps:null}]})'),'');assert.match(visual.run('stickerInternational({theme:"silver",internationalRecords:[{level:"Sub-19",caps:3},{level:"Sub-21",caps:null}]})'),/>3\+<\/b>/);await visual.run('AutoSave.settle()');
 const factory=new IDBFactory(),a=await open(factory);assert(a.$('appVersion').textContent.includes(require('../package.json').version.split('.').slice(0,2).join('.')));a.run('enterDatabase()');assert(a.w.document.querySelector('.database-health'));
 a.w.document.querySelector('[data-health="noBirth"]').click();assert.equal(a.$('search-birth').value,'missing');a.$('searchClear').click();assert.equal(a.$('search-birth').value,'all');
 a.run('openDatabaseSearch("staff")');assert(a.$('global-results').querySelector('[data-global-type="staff"]'));a.$('global-results').querySelector('[data-global-type="staff"]').click();assert(a.$('staffCard'));a.run('closeRecord()');
 a.run('openDatabaseSearch("competitions")');a.$('global-results').querySelector('[data-global-type="competitions"]').click();assert(a.w.document.querySelector('[data-competition-card]'));
 a.run('openFilteredPlayers()');a.$('viewCards').click();assert(a.$('searchResults').querySelector('.sticker'));const card=a.$('searchResults').querySelector('[data-search-player]');card.click();assert(a.$('playerIdentityHeader'));a.$('pt-carreira').click();assert.match(a.$('playerTimeline').textContent,/Data por indicar/);a.$('playerCancel').click();a.$('viewTable').click();const col=a.w.document.querySelector('[data-player-column="1"]');col.checked=false;col.dispatchEvent(new a.w.Event('change'));assert(a.$('searchResults').querySelector('th:nth-child(2)').hidden);col.checked=true;col.dispatchEvent(new a.w.Event('change'));
 a.run('master.players[0].photo="data:image/png;base64,AAAA";view="Plantel e staff";editorClub=master.players[0].club;render()');assert(a.$('app').querySelector('img.staff-thumb'));a.run('view="Editor de clubes";render()');assert(a.$('app').querySelectorAll('.club-league-separator').length>=4);assert.equal(a.$('app').querySelectorAll('.club-photo-card').length,a.run('master.clubs.length'));
 a.run('openPlayer(master.players[0].id)');const before=a.run('JSON.stringify(master.players[0])');a.$('source-title').value='Fonte cancelada';a.$('source-apply').click();a.$('playerCancel').click();assert.equal(a.run('JSON.stringify(master.players[0])'),before);
 a.run('openPlayer(master.players[0].id)');a.$('source-title').value='Federação';a.$('source-url').value='https://example.org/federation';a.$('source-field').value='international';a.$('source-status').value='Confirmado';a.$('source-date').value='2026-09-13';
 a.$('playerForm').dispatchEvent(new a.w.Event('submit',{cancelable:true}));assert(!a.$('playerEditor').open);assert.equal(a.run('master.players[0].documentSources[0].field'),'international');assert.equal(a.run('master.players[0].verificationStatus||"Por verificar"'),'Confirmado');await a.run('AutoSave.settle()');
 const b=await open(factory);assert.equal(b.run('master.players[0].documentSources[0].title'),'Federação');b.run('enterDatabase();openPlayer(master.players[0].id)');assert.match(b.$('documentSources').textContent,/Federação/);assert.match(b.$('documentCompleteness').textContent,/critérios documentais/);
 b.$('source-title').value='Insegura';b.$('source-url').value='javascript:alert(1)';b.$('source-apply').click();assert.match(b.$('source-error').textContent,/URL/);assert.equal(b.run('playerDraft.documentSources.length'),1);
 b.$('source-reset').click();b.$('documentSources').querySelector('[data-source-edit]').click();b.$('source-title').value='Federação revista';b.$('source-apply').click();assert.equal(b.run('playerDraft.documentSources[0].title'),'Federação revista');b.$('playerCancel').click();assert.equal(b.run('master.players[0].documentSources[0].title'),'Federação');
 const bulk=await open(new IDBFactory());bulk.run('enterDatabase();openFilteredPlayers()');
 const baseline=bulk.run('JSON.stringify(master)');bulk.$('searchResults').querySelector('[data-bulk-id]').click();bulk.$('bulkOpen').click();bulk.$('bulkValue').value='Parcial';bulk.$('bulkForm').dispatchEvent(new bulk.w.Event('submit',{cancelable:true}));assert(!bulk.$('bulkConfirm').hidden);assert.equal(bulk.run('JSON.stringify(master)'),baseline);bulk.$('bulkClose').click();assert.equal(bulk.run('JSON.stringify(master)'),baseline);
 bulk.$('bulkOpen').click();bulk.$('bulkValue').value='Parcial';bulk.$('bulkForm').dispatchEvent(new bulk.w.Event('submit',{cancelable:true}));bulk.$('bulkConfirm').click();assert.equal(bulk.run('master.players.filter(p=>p.verificationStatus==="Parcial").length'),1);assert.equal(bulk.run('selectedPlayers.size'),0);await bulk.run('AutoSave.settle()');
 bulk.run('showClub(master.clubs[0].id)');assert.equal(bulk.$('clubDetails').querySelectorAll('.club-facts-grid .club-info-section').length,2);const people=bulk.$('clubDetails').querySelectorAll('.person-row');assert(people.length>0);assert([...people].every(row=>row.querySelector('.person-avatar')));
 const imp=await open(new IDBFactory());imp.run('enterDatabase();openCsvImport()');
 async function loadCsv(text){Object.defineProperty(imp.$('csvImportFile'),'files',{configurable:true,value:[{size:text.length,text:async()=>text}]});await imp.$('csvImportFile').onchange({target:imp.$('csvImportFile')});}
 const oldHeight=imp.run('master.players[0].height'),pid=imp.run('master.players[0].id');
 await loadCsv(`id;height\n${pid};183`);assert(!imp.$('csvImportConfirm').hidden);assert.equal(imp.run('master.players[0].height'),oldHeight);imp.$('csvImportClose').click();assert.equal(imp.run('master.players[0].height'),oldHeight);
 imp.run('openCsvImport()');await loadCsv(`id;height\n${pid};183`);imp.$('csvImportConfirm').click();assert.equal(imp.run('master.players[0].height'),183);await imp.run('AutoSave.settle()');
 imp.run('openCsvImport()');await loadCsv(`id;height\n${pid};184`);imp.run('master.players[0].weight=81');imp.$('csvImportConfirm').click();assert.match(imp.$('csvImportError').textContent,/base mudou/);assert.equal(imp.run('master.players[0].height'),183);imp.$('csvImportClose').click();
 imp.run('openPlayer(master.players[0].id)');const zoom=imp.$('playerForm').elements.namedItem('photoZoom');zoom.value='140';zoom.dispatchEvent(new imp.w.Event('input',{bubbles:true}));assert.equal(imp.run('playerDraft.photoZoom'),140);assert.notEqual(imp.run('master.players[0].photoZoom'),140);imp.$('playerForm').dispatchEvent(new imp.w.Event('submit',{cancelable:true}));assert.equal(imp.run('master.players[0].photoZoom'),140);imp.run('openPlayer(master.players[0].id)');assert.equal(imp.$('playerForm').elements.namedItem('photoZoom').value,'140');imp.$('resetPhotoFrame').click();assert.equal(imp.run('playerDraft.photoZoom'),100);imp.$('playerCancel').click();assert.equal(imp.run('master.players[0].photoZoom'),140);
 const journeyFactory=new IDBFactory(),j=await open(journeyFactory);j.run('enterDatabase();openPlayer(master.players[0].id)');const clubBefore=j.run('playerDraft.club');
 j.$('hist-club').value='new';j.$('hist-club').dispatchEvent(new j.w.Event('change'));j.$('hist-clubName').value='Clube de teste estrangeiro';j.$('hist-clubCountry').value='Portugal';j.$('hist-start').value='2020-07-01';j.$('hist-end').value='2021-06-30';j.$('historyApply').click();assert.equal(j.run('playerDraft.contractHistory.length'),1);assert.equal(j.run('master.players[0].contractHistory'),undefined);assert.equal(j.run('playerDraft.club'),clubBefore);assert.match(j.$('playerTimeline').textContent,/Clube de teste estrangeiro/);
 j.$('playerCancel').click();assert.equal(j.run('master.documentaryClubs'),undefined);
 j.run('openPlayer(master.players[0].id)');j.$('hist-club').value='new';j.$('hist-clubName').value='Clube de teste estrangeiro';j.$('hist-clubCountry').value='Portugal';j.$('hist-start').value='2020-07-01';j.$('hist-end').value='2021-06-30';j.$('historyApply').click();j.$('playerForm').dispatchEvent(new j.w.Event('submit',{cancelable:true}));assert(!j.$('playerEditor').open);assert.equal(j.run('master.documentaryClubs.length'),1);assert.equal(j.run('master.players[0].club'),clubBefore);await j.run('AutoSave.settle()');
 const persisted=await open(journeyFactory);assert.equal(persisted.run('master.documentaryClubs[0].country'),'Portugal');
 j.run('openPlayer(master.players[0].id)');assert(j.$('hist-club').textContent.includes('Clube de teste estrangeiro'));j.$('historyRows').querySelector('[data-history-edit]').click();j.$('hist-end').value='2022-06-30';j.$('historyApply').click();assert.equal(j.run('playerDraft.contractHistory[0].contractEnd'),'2022-06-30');
 j.$('addDocumentaryStats').click();j.$('hist-club').value='external:0';j.$('hist-season').value='2021/22';j.$('hist-appearances').value='12';j.$('hist-goals').value='3';j.$('hist-source').value='Arquivo';j.$('historyApply').click();assert.equal(j.run('playerDraft.documentaryStats[0].goals'),3);assert.equal(j.run('playerDraft.stats'),undefined);
 j.$('playerForm').elements.namedItem('nation').value='Suíça';j.$('playerForm').elements.namedItem('secondNation').value='Portugal';j.$('playerForm').dispatchEvent(new j.w.Event('input',{bubbles:true}));assert.equal(j.$('playerIdentityHeader').querySelectorAll('.dual-nationality img').length,2);
 const oldId=j.run('playerId');j.$('playerNext').click();assert(j.$('navStay'));j.$('navStay').click();assert.equal(j.run('playerId'),oldId);j.$('playerNext').click();j.$('navSave').click();assert.notEqual(j.run('playerId'),oldId);assert.equal(j.run('master.players[0].documentaryStats[0].goals'),3);
 j.$('playerPrevious').click();assert.equal(j.run('playerId'),oldId);j.$('historyRows').querySelector('[data-history-remove]').click();j.$('auditClear').click();j.$('playerForm').dispatchEvent(new j.w.Event('submit',{cancelable:true}));assert.equal(j.run('master.players[0].contractHistory.length'),0);j.run('openPlayer(master.players[0].id)');assert.equal(j.$('pt-timeline'),null);assert.equal(j.$('playerForm').elements.namedItem('verificationStatus'),null);assert.match(j.$('documentSources').textContent,/Fontes e verificação/);j.$('playerCancel').click();
 imp.run('openCsvImport()');imp.$('csvImportType').value='documentaryStatistics';imp.$('csvImportType').dispatchEvent(new imp.w.Event('change'));await loadCsv(`player_id;index;season;club;appearances\n${pid};NOVO;2025/26;0;9`);assert(!imp.$('csvImportConfirm').hidden);assert.equal(imp.run('master.players[0].documentaryStats'),undefined);imp.$('csvImportConfirm').click();assert.equal(imp.run('master.players[0].documentaryStats[0].appearances'),9);
 imp.run('openCsvImport()');imp.$('csvImportType').value='documentaryStatistics';imp.$('csvImportType').dispatchEvent(new imp.w.Event('change'));await loadCsv(`player_id;index;appearances\n${pid};0;11`);imp.$('csvImportType').value='players';imp.$('csvImportType').dispatchEvent(new imp.w.Event('change'));assert(imp.$('csvImportConfirm').hidden);assert.equal(imp.run('csvImportReview'),null);imp.$('csvImportClose').click();
 j.run('openPlayer(master.players[0].id)');assert.equal(j.$('headerAvg').textContent,j.run('String(Engine.gameOverall(playerDraft))'));assert.equal(j.$('headerPotential').textContent,'—');j.$('identityClubLink').click();assert(!j.$('playerEditor').open);assert.equal(j.run('playerFilters.club'),String(clubBefore));
 j.run('openPlayer(master.players[0].id)');j.$('playerForm').elements.namedItem('name').value='Nome pendente';j.$('playerIdentityHeader').querySelector('[data-identity-nation]').click();assert(j.$('navStay'));j.$('navStay').click();assert(j.$('playerEditor').open);j.$('playerIdentityHeader').querySelector('[data-identity-nation]').click();j.$('navDiscard').click();assert.equal(j.run('playerFilters.nation'),'ch');assert.notEqual(j.run('master.players[0].name'),'Nome pendente');
 j.run('career=World.createCareer(master,12);mode="career";s=career;openPlayer(s.players[0].id)');j.$('identityClubLink').click();assert.equal(j.run('mode'),'career');assert(j.$('identityFilteredPlayers').open);j.$('identityFilteredPlayers').querySelector('[data-identity-player]').click();assert(j.$('playerEditor').open);j.$('playerCancel').click();
 imp.run('openCsvImport()');assert.equal(imp.$('csvImportType').options.length,9);assert(imp.$('csvTemplate'));imp.$('csvImportType').value='staff';imp.$('csvImportType').dispatchEvent(new imp.w.Event('change'));const staffBefore=imp.run('master.staff.length');await loadCsv('id;name;role;club\nNOVO;Analista importado;Analista;0');assert(!imp.$('csvImportConfirm').hidden);assert.equal(imp.run('master.staff.length'),staffBefore);assert.match(imp.$('csvImportReview').textContent,/NOVO/);imp.$('csvImportConfirm').click();assert.equal(imp.run('master.staff.length'),staffBefore+1);await imp.run('AutoSave.settle()');
 if(process.argv[2]){const preview=await open(new IDBFactory(),fs.readFileSync(process.argv[2],'utf8'));preview.run('enterDatabase()');assert(preview.w.document.querySelector('.database-health'));assert.match(preview.run('flagAsset("ch")'),/^data:image\/svg/);}
 console.log('PASS: dashboard drill-down, global record navigation, source save/cancel/edit/URL safety, persistence reload and optional standalone preview.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{for(const w of windows){if(w.settleForTest)await w.settleForTest();w.close();}});
