const assert=require('node:assert/strict');const E=require('../dist/game.js');
function setup(){const s=E.fresh();const m=E.startRound(s,321);return {s,m};}
function tick(s,m,n){for(let i=0;i<n;i++){m.paused=false;E.stepMatch(s,m);}}
// Same career, seed, decisions: identical minute events and RNG state, including after save/import.
let {s,m}=setup();const frozen=JSON.stringify(m);assert.equal(E.stepMatch(s,m),false);assert.equal(JSON.stringify(m),frozen);tick(s,m,23);const resumed=E.validate(JSON.parse(JSON.stringify(s)));tick(s,m,7);tick(resumed,resumed.liveMatch,7);assert.deepEqual(m,resumed.liveMatch);
let side=m.teams.find(t=>t.id===s.managed),out=side.active.find(id=>side.roles[id]!=='GR'&&!side.units[id].injuryMatches),incoming=side.bench[0];let force=E.profile(s,m,side);E.changeTactics(s,m,side.id,'4-4-2','Ofensiva');let changed=E.profile(s,m,side);assert.notDeepEqual(force,changed);assert.equal(side.active.length,new Set(side.active).size);E.substitute(s,m,side.id,out,incoming);assert.ok(!side.active.includes(out));assert.ok(side.active.includes(incoming));assert.throws(()=>E.substitute(s,m,side.id,incoming,out));assert.throws(()=>E.updatePlayer(s,out,{quality:99}));
let at=m.minute;E.playToEnd(s,m);assert.equal(m.minute,90);assert.equal(side.units[out].minutes,at);assert.ok(side.units[incoming].minutes<=90-at);assert.equal(E.stepMatch(s,m),false);E.validate(s);const beforeGoals=side.stats.goals;E.finishRound(s);assert.equal(s.round,1);assert.equal(E.finishRound(s),false);assert.equal(E.table(s,s.clubs.find(c=>c.id===s.managed).div).find(c=>c.id===s.managed).gf,beforeGoals);E.validate(s);
// Every team counter agrees with participant totals and event-derived scores for many seeds.
let goals=0,red=0,injuries=0;
for(let seed=1;seed<=40;seed++){let state=E.fresh();let fixture=state.fixtures[1][0].find(f=>f.home===12||f.away===12);let a=E.startMatch(state,fixture,seed),b=E.startMatch(state,fixture,seed);E.playToEnd(state,a);E.playToEnd(state,b);assert.deepEqual(a,b);E.validateMatch(state,a);for(const t of a.teams){for(const k of E.statKeys)assert.equal(t.stats[k],Object.values(t.units).reduce((n,u)=>n+u[k],0));goals+=t.stats.goals;red+=t.stats.red;injuries+=t.stats.injuries;for(const [id,u] of Object.entries(t.units)){assert.ok(u.minutes<=90);if(u.red)assert.ok(!t.active.includes(+id));}}assert.equal(a.teams[0].stats.possession+a.teams[1].stats.possession,270);}
assert.ok(goals>20&&goals<240);assert.ok(red>0);assert.ok(injuries>0);
// Position fit, direct attribute effects, keeper specialisation and fatigue.
let state=E.fresh(),live=E.startRound(state,100),team=live.teams[0],player=state.players.find(p=>p.id===team.active.find(id=>team.roles[id]!=='GR'));
assert.ok(E.fit({...player,position:'PL',secondaryPositions:['DC']},'DC')>E.fit({...player,position:'PL',secondaryPositions:[]},'DC'));
let before=E.profile(state,live,team);for(const id of team.active)team.units[id].fatigue=80;assert.ok(E.profile(state,live,team).attack<before.attack);for(const id of team.active)team.units[id].fatigue=0;
let keeper=state.players.find(p=>p.id===team.active.find(id=>team.roles[id]==='GR'));keeper.attributes={gkReflexes:1,gkHandling:1,gkOneOnOne:1,positioning:1};let weak=E.profile(state,live,team).keeper;keeper.attributes={gkReflexes:20,gkHandling:20,gkOneOnOne:20,positioning:20};assert.ok(E.profile(state,live,team).keeper>weak);
// Five substitutions maximum and no phantom eleventh player after an expulsion.
let test=setup(),t=test.m.teams.find(t=>t.id===test.s.managed);for(let n=0;n<5;n++)E.substitute(test.s,test.m,t.id,t.active[n],t.bench[0]);assert.throws(()=>E.substitute(test.s,test.m,t.id,t.active[6],t.bench[0]));let expelled=t.active.pop();t.units[expelled].red=1;delete t.roles[expelled];E.changeTactics(test.s,test.m,t.id,'3-5-2','Defensiva');assert.equal(t.active.length,10);
// Import rejection without overwriting the working career.
let broken=structuredClone(state);broken.liveMatch.teams[0].active.push(99999);assert.throws(()=>E.validate(broken));broken=structuredClone(state);broken.liveMatch.rng='bad';assert.throws(()=>E.validate(broken));
// Whole-season legacy data + promotion, player archives and old/new saved games.
let season=E.fresh();const unavailable=season.players.find(p=>p.club===12);unavailable.injuryMatches=1;for(let r=0;r<22;r++){E.advance(season,()=>.25);E.validate(season);if(r===0){assert.equal(unavailable.stats,undefined);assert.equal(unavailable.injuryMatches,0);}}let top=E.table(season,1)[0].id,down=E.table(season,0).at(-1).id;E.nextSeason(season);assert.equal(season.clubs.find(c=>c.id===top).div,0);assert.equal(season.clubs.find(c=>c.id===down).div,1);assert.equal(season.year,2027);assert.equal(season.players[0].career.length,1);assert.ok(season.history[0].reports.length>0);E.validate(JSON.parse(JSON.stringify(season)));
console.log(`PASS: deterministic/resumable match, controls, substitutions, event/stat consistency, goalkeeper, fatigue, cards (${red}), injuries (${injuries}), ${goals} goals in 40 matches, full season and promotion.`);
